apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-for-cicd
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main:image-updater-{{.SHA256}}
    argocd-image-updater.argoproj.io/image-list: my-image=ghcr.io/ta8i2chi8/sample-app-for-cicd
    argocd-image-updater.argoproj.io/my-image.update-strategy: latest
    argocd-image-updater.argoproj.io/my-image.ignore-tags: latest
spec:
  project: default
  destination:
    namespace: sample-app-for-cicd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ta8i2chi8/sample-app-for-cicd-manifests
    targetRevision: main
    path: app/overlays/prd
  syncPolicy:
    automated:
      prune: true